# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  projeto-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: projeto-mysql
    volumes:
      - projeto-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=projeto
      - MYSQL_DATABASE=projeto
      - MYSQL_USER=projeto
      - MYSQL_PASSWORD=projeto

  # PHP 7.3 + nginx
  app:
    image: ambientum/php:latest-nginx
    container_name: projeto-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql